# Generated by Django 4.1.5 on 2023-01-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('is_business', models.BooleanField(default=False)),
            ],
        ),
    ]
