# Generated by Django 4.1.4 on 2023-01-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('phone', models.PositiveIntegerField()),
                ('is_business', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=10)),
                ('profileIntroduce', models.TextField(max_length=200)),
            ],
        ),
    ]
