# Generated by Django 4.1.7 on 2023-03-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_rename_reveiw_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="experiences",
            new_name="experience",
        ),
    ]
