# Generated by Django 4.1.5 on 2023-01-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('lecturetime', models.DateTimeField()),
                ('book', models.CharField(max_length=20)),
            ],
        ),
    ]
