# Generated by Django 4.1.4 on 2023-01-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(max_length=100)),
                ('like', models.PositiveIntegerField()),
                ('content', models.TextField(max_length=300)),
            ],
        ),
    ]
