# Generated by Django 4.1.4 on 2023-01-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_feed_content_alter_feed_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
