# Generated by Django 2.2 on 2023-06-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0006_post_alter_title_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='item_price_range',
            field=models.CharField(choices=[('H', 'High'), ('M', 'medium'), ('L', 'Low')], default=None, max_length=10, null=True),
        ),
    ]
