# Generated by Django 2.2 on 2023-06-29 14:11

from django.db import migrations


def convert_to_price_range(price: int) -> str:
    """가격을 범위로 바꿔주는 함수"""
    if price <= 10000:
        return "L"
    elif price <= 100000:
        return "M"
    else:
        return "H"


def save_item_price_range(apps, schema_editor):
    """item_price_range 필드에 값을 저장해 주는 함수"""
    Post = apps.get_model("podomarket", "Post")
    for post in Post.objects.all():
        post.item_price_range = convert_to_price_range(post.item_price)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0007_post_item_price_range'),
    ]

    operations = [
        migrations.RunPython(save_item_price_range, migrations.RunPython.noop)
    ]
