# Generated by Django 4.1.4 on 2023-01-06 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="feed",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="feeds.feed"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="reply",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.CharField(max_length=120),
        ),
    ]
