# Generated by Django 4.1.4 on 2023-01-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120)),
                ('like', models.PositiveIntegerField()),
                ('reply', models.BooleanField(default=False)),
            ],
        ),
    ]
