# Generated by Django 4.1.4 on 2023-01-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=120),
        ),
    ]
