# Generated by Django 2.2 on 2023-02-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
