# Generated by Django 4.1.4 on 2023-01-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="SNS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=150)),
                ("token", models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
